-- Intentionally empty.
--
-- This migration previously referenced tables created by later migrations and
-- used unsupported `CREATE POLICY IF NOT EXISTS` syntax. Compatible definitions
-- now live in 20260704120000_security_fixes.sql.
